# Generated by Django 2.0.4 on 2018-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_in',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
