# Generated by Django 2.0.4 on 2018-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
